CREATE DATABASE GARVA;
USE GARVA;

CREATE TABLE CLIENTE
(
	PK_ID_CLIENTE 		INT UNSIGNED AUTO_INCREMENT ,
    NOMBRE_CLIENTE 		VARCHAR(255) NOT NULL,
    APELLIDO_CLIENTE 	VARCHAR(255) NOT NULL,
    DIRECCION_CLIENTE 	VARCHAR(255) ,
    TELEFONO_CLIENTE 	VARCHAR(20),
    CORREO_CLIENTE 		VARCHAR(255),
						PRIMARY KEY(PK_ID_CLIENTE)
);

CREATE TABLE EMPLEADO
(
	PK_ID_EMPLEADO 				INT UNSIGNED AUTO_INCREMENT ,
    NOMBRE_EMPLEADO				VARCHAR(255) NOT NULL,
    APELLIDO_EMPLEADO 			VARCHAR(255) NOT NULL,
	DIRECCION_EMPLEADO 			VARCHAR(255) NOT NULL,
    TELEFONO_EMPLEADO 			VARCHAR(20) NOT NULL,
    ROL_EMPLEADO 				ENUM("CAJERA","COCINERO","CONTADORA") DEFAULT "CAJERA",
    FECHA_CONTRATACION_EMPLEADO DATE NOT NULL,
								PRIMARY KEY(PK_ID_EMPLEADO)
);

CREATE TABLE BOLETA
(
	PK_ID_BOLETA	INT UNSIGNED AUTO_INCREMENT,
    NRO_BOLETA	    VARCHAR(255) UNIQUE NOT NULL ,
    FECHA_BOLETA	DATETIME DEFAULT CURRENT_TIMESTAMP(),
    IGV				DECIMAL(5,2) UNSIGNED NOT NULL,
    FK_ID_CLIENTE 	INT UNSIGNED NOT NULL,
    FK_ID_EMPLEADO  INT UNSIGNED NOT NULL,
    
					PRIMARY KEY(PK_ID_BOLETA),
					INDEX(FK_ID_CLIENTE),
					INDEX(FK_ID_EMPLEADO)
);

ALTER TABLE BOLETA ADD  FOREIGN KEY(FK_ID_CLIENTE) REFERENCES CLIENTE(PK_ID_CLIENTE);
ALTER TABLE BOLETA ADD FOREIGN KEY(FK_ID_EMPLEADO) REFERENCES EMPLEADO(PK_ID_EMPLEADO);

CREATE TABLE MENU
(
	PK_ID_MENU INT UNSIGNED AUTO_INCREMENT ,
    FECHA_MENU DATETIME DEFAULT CURRENT_TIMESTAMP() ,
    STOCK_MENU INT UNSIGNED DEFAULT(0)NOT NULL,
    PRECIO_MENU DECIMAL(11,3) UNSIGNED NOT NULL,
				PRIMARY KEY(PK_ID_MENU)
);

CREATE TABLE PEDIDO 
(
	PK_ID_PEDIDO INT UNSIGNED AUTO_INCREMENT,
    FECHA_PEDIDO DATETIME DEFAULT CURRENT_TIMESTAMP(),
    CANTIDAD 	 INT UNSIGNED UNSIGNED NOT NULL,
    FK_ID_MENU 	 INT UNSIGNED UNSIGNED NOT NULL,
				 PRIMARY KEY(PK_ID_PEDIDO),
				 INDEX(FK_ID_MENU)
);

ALTER TABLE PEDIDO ADD FOREIGN KEY(FK_ID_MENU) REFERENCES MENU(PK_ID_MENU);


CREATE TABLE DETALLE_BOLETA_PEDIDO
(
	PK_ID_DETALLE_PEDIDO INT UNSIGNED AUTO_INCREMENT,
    FK_ID_PEDIDO		 INT UNSIGNED NOT NULL,
    FK_ID_BOLETA		 INT UNSIGNED NOT NULL,
    TOTAL 				 DECIMAL(11,3) UNSIGNED NOT NULL,
    RESTO 				 DECIMAL(11,3) UNSIGNED NOT NULL,
						 PRIMARY KEY(PK_ID_DETALLE_PEDIDO),
                         INDEX(FK_ID_PEDIDO),
                         INDEX(FK_ID_BOLETA)
);

ALTER TABLE DETALLE_BOLETA_PEDIDO ADD FOREIGN KEY(FK_ID_PEDIDO) REFERENCES PEDIDO(PK_ID_PEDIDO);
ALTER TABLE DETALLE_BOLETA_PEDIDO ADD FOREIGN KEY(FK_ID_BOLETA) REFERENCES BOLETA(PK_ID_BOLETA);

CREATE TABLE VENTAS_DIARIAS
(
	FK_VENTA_DIARIA INT UNSIGNED NOT NULL,
    TOTAL_VENTAS	DECIMAL(10,2) UNSIGNED NOT NULL
);
ALTER TABLE VENTAS_DIARIAS ADD FOREIGN KEY(FK_VENTA_DIARIA) REFERENCES MENU(PK_ID_MENU) ;

CREATE TABLE USUARIOS
(
	PK_ID_USUARIO 		INT UNSIGNED AUTO_INCREMENT,
    NOMBRE_USUARIO	 	VARCHAR(255) UNIQUE NOT NULL,
    CONTRASENIA 		VARCHAR(255) NOT NULL,
    ESTADO 				BOOLEAN DEFAULT TRUE,
    CORREO 				VARCHAR(255),
    FK_ID_EMPLEADO		INT  UNSIGNED NOT NULL UNIQUE,
						INDEX(FK_ID_EMPLEADO),
						PRIMARY KEY (PK_ID_USUARIO)
);

ALTER TABLE USUARIOS ADD FOREIGN KEY(FK_ID_EMPLEADO) REFERENCES EMPLEADO(PK_ID_EMPLEADO) ;